### ISSUE TITLE
Tracking issue for bit arrays on javascript target

### ISSUE THREAD

**Issue by GearsDatapacks** [gleam-lang/gleam#3842]
There are still many features of bit arrays that are not yet implemented on the javascript target. We want to have all of them eventually, but it's a lot to implement in one go, and a lot to have a separate issue for each one. So I've decided to create a tracking issue to list them all, and these can be slowly ticked off when people implement specific features.

- [ ] Non-utf8 strings: `utf16`, `utf32`, `utf16_codepoint` and `utf32_codepoint`
- [ ] Signedness: `signed` and `unsigned`
- [ ] Endianness: Missing `native`
- [ ] Unit specification: `unit`
- [ ] Non-constant sizes when pattern matching: `<<bits:size(some_variable)>>`
- [ ] Non byte-aligned segments
- [ ] Non byte-aligned access

Please let me know if I've missed any. I'm not super familiar with bit array syntax so I mostly just looked through the compiler and found where an error was thrown on javascript.

**Comment by richard-viney** [comment]
Good to have a tracking issue for this. I've been slowly improving the bit array experience in JS this year, both in features and performance. I believe I got to full signedness support in Gleam 1.4, unless there's still a gap somewhere?

What's your sense as to which of the missing bit array features on JS are the highest value to support? If you were to order them, what are the top items? I suspect it's the last 3 in the above list (dynamic sizes when matching, and removing the byte-alignment constraints).

16-bit floats can go on the list of unsupported features on JS too.

**Comment by richard-viney** [comment]
16-bit floats are added in https://github.com/gleam-lang/gleam/pull/4349

**Comment by ImmemorConsultrixContrarie** [comment]
Hmm, there's [TypedArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray) which uses native endian. Not sure if it can directly map to bit array. Worst case scenario it can be used to detect host endian:
```js
let uInt32 = new Uint32Array([0x11223344]);
let uInt8 = new Uint8Array(uInt32.buffer);

if(uInt8[0] === 0x44) {
    return 'Little Endian';
} else {
    return 'Big Endian';
}
```

**Comment by GearsDatapacks** [comment]
Yeah, I've looked into this before, and that's more or less how I was thinking about doing it. The tricky parts are the other bits of JavaScript code generation which currently rely on knowing endianness at compile-time.
